### PR TITLE
Initial cm-13.0 bringup for taoshan

### PR DESCRIPTION
**Pull request by Incredible-O**

### CODE REVIEW

**Comment by chirayudesai** [comment]
You could consider using a shim lib for the qc-opt update (https://github.com/CyanogenMod/android_device_asus_mofd-common/blob/cm-13.0/libshims/icu53.c)

While there are some issues with shims and ctors/dtors right now, this is worth a try.

**Comment by Incredible-O** [comment]
Thanks, shimming libqc-opt.so works too. I think this is good to go now

**Comment by chirayudesai** [comment]
I see some removals in the makefiles, but those files aren't actually removed.
Even if those are symlinks, could you remove them?

A scripted run of removing anything that's not in the list would do too.

**Comment by Incredible-O** [comment]
Should be good now.

**Pull request merged**
