### PR TITLE
Initial Bringup - Tulip Vendor files

### PR DESCRIPTION
**Pull request by renj1ete0**
Might not be enough or might be too much. This is my first time doing this and I'm not really sure about it. I've used oppo's msm8939-common proprietary-files.txt as a rough gauge

### CODE REVIEW

**Comment by chirayudesai** [comment]
That is a good starting point, however for certain sony specific things looking at a sony device will help.
There's Sony AOSP too for blobs.

Do you have it booting?

One thing though, it isn't currently supported by FXP due to not having an official unlock method.

**Comment by renj1ete0** [comment]
I just released a first test build to Xperia M4, will update you again. 

For unlocking methods users confirmed u can select Xperia M or Xperia M2, and then typing in details to obtain unlock keys, but yea its unofficial 'unlock' but it works. I have no idea why Sony isn't supporting a Qualcomm device that is capable much more, really contradicts with their open device policy but oh well. 

Sony AOSP doesn't have quite a few blobs so we do require vendor, i will try to filter and reduce the amt of blobs required

Will update you again once more once i have more.

**Comment by championswimmer** [comment]
I think Alin is working on that (making the unlock official)

I am probably getting my M4 in some days too.
Will check in with the bringup asap.

**Comment by chirayudesai** [comment]
Yes, you can obtain the keys that way, and that has been used in the past for other devices.
The issue here is that the bootloader doesn't allow running fastboot oem unlock, so you have to resort to an unofficial way.

A bootloader update would fix it, and I would assume it would come with the next major update, but given that Sony is skipping 5.1 for 6.0, we might have to wait a little bit longer.

**Comment by renj1ete0** [comment]
Hopefully, update now is currently not booting, i'm trying to get logs soon so i can fix this asap

**Comment by chirayudesai** [comment]
I'll close this for now.

Feel free to contact me on IRC (freenode handle cdesai) or hangouts (same e-mail as used for git)

**Pull request closed without merging**
