### PR TITLE
ivy: Update to 32.3.A.0.376

### PR DESCRIPTION
**Pull request by Quarx2k**

### CODE REVIEW

**Comment by jerpelea** [comment]
afaik this release ia no longer available because it had issues!

**Comment by Quarx2k** [comment]
Why? This rom still available for download. I checked now.

**Comment by airlessproject** [comment]
No this is the re-release. 372 was the one that was pulled

**Comment by jerpelea** [comment]
in flashtool?

**Comment by airlessproject** [comment]
Or you mean both 372 and 376 will be pulled?

**Comment by Quarx2k** [comment]
Xperiafirm  - E6533 - 32.3.A.0.376  http://i.imgur.com/tMW7yTC.png

**Comment by jerpelea** [comment]
ok..my bad

**Comment by Quarx2k** [comment]
But which problems this rom have?

**Pull request closed without merging**
