### PR TITLE
sumire: Update blobs from 32.4.A.0.160

### PR DESCRIPTION
**Pull request by HaoZeke**
No changes required. Fresh from the ./extract_files.sh script.

Change-Id: I21eabe0d50bc6423ab02efee90b392bcbb57e98d

### CODE REVIEW

**Comment by HaoZeke** [comment]
Actually please don't merge this yet... lib_get_secure_mode.so has been removed in this version and I need to test if it's required.

**Comment by HaoZeke** [comment]
Updated and build tested. Should be ok to merge.

**Comment by forkposix** [comment]
hi what happened vendor/sony/kitakami_common ???

**Comment by HaoZeke** [comment]
Not related to this pull request.. Check gerrit for details about that change.

**Pull request merged**
