### PR TITLE
z3c: Restore working wlan blobs

### PR DESCRIPTION
**Pull request by opticron**
The current (and newer) blobs cause WiFi with WPA2 to be spotty on 2.4GHz and
almost completely non-functionality on 5GHz. This restores the known-
working blobs. Tested on the 20150820 nightly with restored blobs.

### CODE REVIEW

**Comment by opticron** [comment]
I just checked the nightly from October 29th and this is still an issue. Again, restoring the blobs in this PR restores WiFi to full functionality.

**Comment by opticron** [comment]
This is still an issue with the 20160124 nightly and is still resolved by restoring the older blobs.

**Comment by chirayudesai** [comment]
@Kali- could you check if this is still an issue?

While I do have access to a 5Ghz network now, I don't have a z3 or z3c, and z2 / z3tab have worked fine for me.

**Comment by opticron** [comment]
Did this issue get fixed elsewhere or is it just being declared obselete?

**Comment by Incredible-O** [comment]
I'm not sure if cm-12.1 is still being worked on - you should check cm-14.1 branches to see if the issue persists, or talk to the maintainers (@rcstar6696, @tomascus and @nailyk-fr)

**Pull request closed without merging**
