### PR TITLE
Adreno blobs from Xperia Z Android 4.4

### PR DESCRIPTION
**Pull request by stellirin**
Tested on huashan and nicki, good for all krait-200 devices

### CODE REVIEW

**Comment by Bonoboo** [comment]
Please, approve this request.
Now on CM11 for "nicki" (Xperia M) we need to flash this files as patch after every update to get rid graphical artifacts.

**Comment by sssangram14** [comment]
plz merge commits

**Comment by championswimmer** [comment]
Works on SP

**Comment by Incredible-O** [comment]
Works on Xperia L (taoshan)

**Pull request closed without merging**
