### PR TITLE
Cm 11.0 fusion3 consolidation

### PR DESCRIPTION
**Pull request by chirayudesai**

### CODE REVIEW

**Comment by chirayudesai** [comment]
Looks good, but needs some testing on all fusion3 devices before a merge.

Goes with http://review.cyanogenmod.org/#/q/status:open+topic:consolidation,n,z

**Comment by championswimmer** [comment]
I'll test with pollux & dogo  and let you know

**Comment by chirayudesai** [comment]
Last updated on Fri Feb 14 06:46:44 UTC 2014 (force pushed)

**Comment by chirayudesai** [comment]
Rebased on Mon Mar  3 10:22:02 UTC 2014

**Comment by championswimmer** [comment]
Can be merged. No issue this end

**Comment by brinlyau** [comment]
Fine for me on Yuga (and briefly a friends Pollux).

**Comment by stellirin** [comment]
I bet we could go even further and deduplicate to a sony-common for the other krait 200 devices now everyone is on Android 4.3

**Comment by championswimmer** [comment]
4.4 won't release for all together. It'll be a short lived step. I have
nothing against it, just saying it'll not be a long term measure

**Comment by stellirin** [comment]
true that, but we could probably sort out the generic qcom proprietary blobs from the device / platform specific, those don't seem to be dependent on anything (eg GPS)

**Comment by chirayudesai** [comment]
@AdFad666 it would be better to have them per sony platform IMO.

What else is common on those devices (apart from GPS)?

**Pull request merged**
