### PR TITLE
fusion3: update acdbloader and csd-client

### PR DESCRIPTION
**Pull request by ghost**
from mako LRX2

Change-Id: I2d0c75de837c9bbedeb7ddf973c94a729290c30c

This is needed for the yuga/odin calling.

### CODE REVIEW

**Comment by ghost** [comment]
Test on Odin and works really good.

**Comment by ghost** [comment]
Can anyone merge this, is needed for Yuga, Odin and Dogo?

**Comment by ghost** [comment]
https://github.com/adrian-bl-yuga/OBSOLETE_android_hardware_qcom_audio/commit/134a19a4cf1b5cda00c59402dce628d7c7752344

Take a look at what Adrian commit below

**Comment by ghost** [comment]
@chirayudesai, @vware can you look at this? thanks.

**Comment by vware** [comment]
please abandon this. i created a new pull request with the original authors credits intact. also, nothing will be merged before being tested on more platforms.
“Patience you must have, my young padawan”- Master Yoda

**Comment by ghost** [comment]
Because I update to the LR22C is different from the original one.

**Pull request closed without merging**
