### PR TITLE
Sumire Fingerprint Blobs

### PR DESCRIPTION
**Pull request by HaoZeke**
These blobs along with the LineageOS commits fix the Fingerprint Sensor.

Change-Id: I790bff9acbab4f584d39cb0dd1f88ca58ad41a6e

### CODE REVIEW

**Comment by haggertk** [comment]
-1. use the scripts to generate/update makefiles. Do not edit by hand.

**Comment by Myself5** [comment]
I'd suggest squashing the commits ^

**Comment by HaoZeke** [comment]
Squashed

**Comment by chirayudesai** [comment]
Better commit message please.

Also, there's a big makefile change, put that in another commit.

So, two commits
1) sumire: Regenerate makefiles
2) sumire: Add stock fingerprint blobs

Stock version: 32.blah

**Comment by Myself5** [comment]
hahhaha... Well sorry @HaoZeke :DD

**Comment by HaoZeke** [comment]
So, for regenerating the makefiles should I actually first remove the fpc files?? o.O

**Comment by chirayudesai** [comment]
Yes.

**Comment by HaoZeke** [comment]
I think that's done now..

**Comment by Myself5** [comment]
extended by #200

**Pull request closed without merging**
