### PR TITLE
taoshan: Fixed low light video rec

### PR DESCRIPTION
**Pull request by Sudokamikaze**

### CODE REVIEW

**Comment by Sudokamikaze** [comment]
This may work also on CM12.1 branch

**Comment by Incredible-O** [comment]
What exactly have you changed or where does this blob come from?

**Comment by Sudokamikaze** [comment]
@olivieer I found this at russian forum called "4pda" in a thread about our device, and the blob was in the zipfile that corrects low FPS when you shoot video in a dark environment
by the way, this zipfile created by @rostifaner
link to the post http://4pda.ru/forum/index.php?showtopic=713597&st=240#entry46921134

**Comment by rostifaner** [comment]
@olivieer 
this come from official sony ROM and its works perfect on CM

**Pull request closed without merging**
